# 模型路径（使用 .engine 文件）
drone_model_path: "/home/thatbbbbbb/projects/aruco_gimbal_project/detect/train/best.engine"
save_path: "/home/thatbbbbbb/projects/aruco_gimbal_project/drone_imgs"
# 输入尺寸（根据上面确认的）
input_width: 640
input_height: 640

# 设备
device: "cuda"

# 检测参数
confidence_threshold: 0.5
nms_threshold: 0.45
min_confidence: 0.3

# ROI 配置（可选）
use_roi: false